restart_file: .na
start_datetime: 2023-03-16 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-03-15 00:00:00
forecast_horizon: 0.0
sim_name: glm_flare_v1
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: false
