restart_file: ALEX-2024-04-01-specified_out.nc
start_datetime: 2024-03-28 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-04-02 00:00:00
forecast_horizon: 30
sim_name: specified_out
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: false
